 var zh = {
            //Report国际化
            'RI_BAO' : '日报',
            'ZHOU_BAO' : '周报',
            'YUE_BAO' : '月报',
            'NIAN_BAO' : '年报',
            'JIN_TIAN' : '今天',
            'QIAN_YI_TIAN' : '前一天',
            'HOU_YI_TIAN' : '后一天',
            'QIAN_YI_YUE' : '前一月',
            'HOU_YI_YUE' : '后一月',
            'QIAN_YI_ZHOU' : '前一周',
            'HOU_YI_ZHOU' : '后一周',
            'QIAN_YI_NIAN' : '前一年',
            'HOU_YI_NIAN' : '后一年',
            'GENG_DUO' : '更多',
            'BEN_ZHOU' : '本周',
            'BEN_YUE' : '本月',
            'JIN_NIAN' : '今年',
            'QUE_DING' : '确定',
            'GUAN_BI' : '关闭',
            'CHANG_ZHAN_RONG_LIANG' : '场站容量',
            'FA_DIAN_LIANG' : '发电量',
            'MAN_FA_XIAO_SHI_SHU' : '满发小时数',
            'GU_ZHANG_SHU' : '故障数',
            'PIN_JUN_WEN_DU' : '平均温度',
            'ZUI_GAO' : '最高',
            'ZUI_DI' : '最低',
            'LEI_JI_FU_ZHAO' : '累计辐照',
            'TIAN_QI' : '天气',
            'CHANG_ZHAN_KE_LI_YONG_LV' : '场站可利用率',
            'NI_BIAN_QI_FA_DIAN_LIANG' : '逆变器发电量',
            'ZUI_JIN_QI_RI_DE_FA_DIAN_LIANG_BI_JIAO' : '最近七日的发电量比较',
            'ZUI_JIN_WU_ZHOU_DE_FA_DIAN_LIANG_BI_JIAO' : '最近五周的发电量比较',
            'BEN_NIAN_DU_MEI_YUE_FA_DIAN_LIANG_BI_JIAO' : '本年度每月发电量比较',
            'NIAN_DU_FA_DIAN_LIANG_BI_JIAO' : '年度发电量比较',
            'DAO_CHU' : '导出',
            'CHANG_ZHAN_FA_DIAN_LIANG' : '场站发电量',
            'QING' : '晴',
            'DUO_YUN' : '多云',
            'ZHEN_YU' : '阵雨',
            'XIAO_YU' : '小雨',
            'ZHONG_YU' : '中雨',
            'YIN' : '阴',
            'BAO_XUE' : '暴雪',
            'BAO_YU' : '暴雨',
            'DA_BAO_YU' : '大暴雨',
            'BAO_YU_ZHUAN_DA_BAO_YU' : '暴雨到大暴雨',
            'DA_BAO_YU_ZHUAN_TE_DA_BAO_YU' : '大暴雨到特大暴雨',
            'DA_XUE' : '大雪',
            'DA_XUE_ZHUAN_BAO_XUE' : '大到暴雪',
            'DA_YU' : '大雨',
            'DA_YU_ZHUAN_BAO_YU' : '大到暴雨',
            'DONG_YU' : '冻雨',
            'FU_CHEN' : '浮尘',
            'LEI_ZHEN_YU' : '雷阵雨',
            'LEI_ZHEN_YU_BAN_YOU_BING_BAO' : '雷阵雨伴有冰雹',
            'QIANG_SHA_CHEN_BAO' : '强沙尘暴',
            'SHA_CHEN_BAO' : '沙尘暴',
            'TE_DA_BAO_YU' : '特大暴雨',
            'WU' : '雾',
            'XIAO_XUE' : '小雪',
            'XIAO_XUE_ZHUAN_ZHONG_XUE' : '小到中雪',
            'XIAO_YU_ZHUAN_ZHONG_YU' : '小到中雨',
            'YANG_SHA' : '扬沙',
            'YU_JIA_XUE' : '雨夹雪',
            'ZHEN_XUE' : '阵雪',
            'ZHONG_XUE' : '中雪',
            'ZHONG_XUE_ZHUAN_DA_XUE' : '中到大雪',
            'ZHONG_YU_ZHUAN_DA_YU' : '中到大雨',
            'MAI' : '霾',
            'NIAN_FORMAT' : '{0}年',
            'YUE_FORMAT' : '{0}年{1}月',
            'ZHOU_FORMAT' : '{0}年 第{1}周',
            'TIAN_FORMAT' : '{0}年{1}月{2}日',
            'SHENG_CHAN_YUN_XING' : '生产运行',
            'AXIS_YUE_FORMAT' : '{0}-{1}',
            'AXIS_TIAN_FORMAT' : '{0}-{1}-{2}',
            'TIAN' : '天'
        };
        
        var en = {
            //Report国际化
            'RI_BAO' : 'Daily',
            'ZHOU_BAO' : 'Weekly',
            'YUE_BAO' : 'Monthly',
            'NIAN_BAO' : 'Yearly',
            'JIN_TIAN' : 'Today',
            'QIAN_YI_TIAN' : 'Previous',
            'HOU_YI_TIAN' : 'Next',
            'QIAN_YI_YUE' : 'Previous',
            'HOU_YI_YUE' : 'Next',
            'QIAN_YI_ZHOU' : 'Previous',
            'HOU_YI_ZHOU' : 'Next',
            'QIAN_YI_NIAN' : 'Previous',
            'HOU_YI_NIAN' : 'Next',
            'GENG_DUO' : 'More',
            'BEN_ZHOU' : 'Current Week',
            'BEN_YUE' : 'Current Month',
            'JIN_NIAN' : 'Current Year',
            'QUE_DING' : 'Done',
            'GUAN_BI' : 'Close',
            'CHANG_ZHAN_RONG_LIANG' : 'Installed Capacity',
            'FA_DIAN_LIANG' : 'Production',
            'MAN_FA_XIAO_SHI_SHU' : 'Full Hours',
            'GU_ZHANG_SHU' : 'Failures',
            'PIN_JUN_WEN_DU' : 'AVG TEMP',
            'ZUI_GAO' : 'Max',
            'ZUI_DI' : 'Min',
            'LEI_JI_FU_ZHAO' : 'Accumulated Irradiation',
            'CHANG_ZHAN_KE_LI_YONG_LV' : 'Availability',
            'NI_BIAN_QI_FA_DIAN_LIANG' : 'Production of Inverter',
            'ZUI_JIN_QI_RI_DE_FA_DIAN_LIANG_BI_JIAO' : 'Production of Last 7 Days',
            'ZUI_JIN_WU_ZHOU_DE_FA_DIAN_LIANG_BI_JIAO' : 'Production of Last 5 Weeks',
            'BEN_NIAN_DU_MEI_YUE_FA_DIAN_LIANG_BI_JIAO' : 'Production of The Year By Month',
            'NIAN_DU_FA_DIAN_LIANG_BI_JIAO' : 'Production of The Years',
            'DAO_CHU' : 'Export',
            'CHANG_ZHAN_FA_DIAN_LIANG' : 'Production of Plant',
            'QING' : 'Sunny',
            'DUO_YUN' : 'Cloudy',
            'ZHEN_YU' : 'Shower Rain',
            'XIAO_YU' : 'Light Rain',
            'ZHONG_YU' : 'Moderate Rain',
            'YIN' : 'Overcast',
            'BAO_XUE' : 'Snowstorm',
            'BAO_YU' : 'Storm',
            'DA_BAO_YU' : 'Heavy Storm',
            'DA_XUE' : 'Heavy Snow',
            'DA_YU' : 'Heavy Rain',
            'BAO_YU_ZHUAN_DA_BAO_YU' : 'Storm to Heavy Storm',
            'DA_BAO_YU_ZHUAN_TE_DA_BAO_YU' : 'Heavy Storm to Severe Storm',
            'DA_XUE_ZHUAN_BAO_XUE' : 'Heavy Snow to Snowstorm',
            'DA_YU_ZHUAN_BAO_YU' : 'Heavy Rain to Storm',
            'DONG_YU' : 'Freezing Rain',
            'FU_CHEN' : 'Dust',
            'LEI_ZHEN_YU' : 'Thundershower',
            'LEI_ZHEN_YU_BAN_YOU_BING_BAO' : 'Hail',
            'QIANG_SHA_CHEN_BAO' : 'Sandstorm',
            'SHA_CHEN_BAO' : 'Duststorm',
            'TE_DA_BAO_YU' : 'Severe Storm',
            'WU' : 'Foggy',
            'XIAO_XUE' : 'Light Snow',
            'XIAO_XUE_ZHUAN_ZHONG_XUE' : 'Light Snow to Moderate Snow',
            'XIAO_YU_ZHUAN_ZHONG_YU' : 'Light Rain to Moderate Rain',
            'YANG_SHA' : 'Sand',
            'YU_JIA_XUE' : 'Sleet',
            'ZHEN_XUE' : 'Snow Flurry',
            'ZHONG_XUE' : 'Moderate Snow',
            'ZHONG_XUE_ZHUAN_DA_XUE' : 'Moderate Snow to Heavy Snow',
            'ZHONG_YU_ZHUAN_DA_YU' : 'Moderate Rain to Heavy Rain',
            'MAI' : 'Haze',
            'TIAN_QI' : 'Weather',
            'NIAN_FORMAT' : '{0}',
            'YUE_FORMAT' : '{1}/{0}',
            'ZHOU_FORMAT' : '{0}FW{1}',
            'TIAN_FORMAT' : '{1}/{2}/{0}',
            'SHENG_CHAN_YUN_XING' : 'OperationReport',
            'AXIS_YUE_FORMAT' : '{1}/{0}',
            'AXIS_TIAN_FORMAT' : '{1}/{2}/{0}',
            'TIAN' : 'day'
            
        };

export function weatherLang(key){
	      	 var _weatherMap = {
            '晴':{'styleName' : 'weather-icon-qing', 'tip' : getString('QING')},
            '多云':{'styleName' : 'weather-icon-duoyun', 'tip' : getString('DUO_YUN')},
            '阵雨':{'styleName' : 'weather-icon-zhenyu', 'tip' : getString('ZHEN_YU')},
            '小雨':{'styleName' : 'weather-icon-xiaoyu', 'tip' : getString('XIAO_YU')},
            '中雨':{'styleName' : 'weather-icon-zhongyu', 'tip' : getString('ZHONG_YU')},
            '阴':{'styleName' : 'weather-icon-yin', 'tip' : getString('YIN')},
            '暴雪':{'styleName' : 'weather-icon-baoxue', 'tip' : getString('BAO_XUE')},
            '暴雨':{'styleName' : 'weather-icon-baoyu', 'tip' : getString('BAO_YU')},
            '大暴雨':{'styleName' : 'weather-icon-dabaoyu', 'tip' : getString('DA_BAO_YU')},
            '暴雨到大暴雨':{'styleName' : 'weather-icon-baoyu-dabaoyu', 'tip' : getString('BAO_YU_ZHUAN_DA_BAO_YU')},
            '大到特大暴雨':{'styleName' : 'weather-icon-dabaoyu-tedabaoyu', 'tip' : getString('DA_BAO_YU_ZHUAN_TE_DA_BAO_YU')},
            '大雪':{'styleName' : 'weather-icon-daxue', 'tip' : getString('DA_XUE')},
            '大到暴雪':{'styleName' : 'weather-icon-daxue-baoxue', 'tip' : getString('DA_XUE_ZHUAN_BAO_XUE')},
            '大雨':{'styleName' : 'weather-icon-dayu', 'tip' : getString('DA_YU')},
            '大到暴雨':{'styleName' : 'weather-icon-dayu-baoyu', 'tip' : getString('DA_YU_ZHUAN_BAO_YU')},
            '冻雨':{'styleName' : 'weather-icon-dongyu', 'tip' : getString('DONG_YU')},
            '浮尘':{'styleName' : 'weather-icon-fuchen', 'tip' : getString('FU_CHEN')},
            '雷阵雨':{'styleName' : 'weather-icon-leizhenyu', 'tip' : getString('LEI_ZHEN_YU')},
            '雷阵雨伴有冰雹':{'styleName' : 'weather-icon-leizhenyuyoubingbao', 'tip' : getString('LEI_ZHEN_YU_BAN_YOU_BING_BAO')},
            '强沙尘暴':{'styleName' : 'weather-icon-qiangshachenbao', 'tip' : getString('QIANG_SHA_CHEN_BAO')},
            '沙尘暴':{'styleName' : 'weather-icon-shachenbao', 'tip' : getString('SHA_CHEN_BAO')},
            '特大暴雨':{'styleName' : 'weather-icon-tedabaoyu', 'tip' : getString('TE_DA_BAO_YU')},
            '雾':{'styleName' : 'weather-icon-wu', 'tip' : getString('WU')},
            '小雪':{'styleName' : 'weather-icon-xiaoxue', 'tip' : getString('XIAO_XUE')},
            '小到中雪':{'styleName' : 'weather-icon-xiaoxue-zhongxue', 'tip' : getString('XIAO_XUE_ZHUAN_ZHONG_XUE')},
            '小到中雨':{'styleName' : 'weather-icon-xiaoyu-zhongyu', 'tip' : getString('XIAO_YU_ZHUAN_ZHONG_YU')},
            '扬沙':{'styleName' : 'weather-icon-yangsha', 'tip' : getString('YANG_SHA')},
            '雨夹雪':{'styleName' : 'weather-icon-yujiaxue', 'tip' : getString('YU_JIA_XUE')},
            '阵雪':{'styleName' : 'weather-icon-zhenxue', 'tip' : getString('ZHEN_XUE')},
            '中雪':{'styleName' : 'weather-icon-zhongxue', 'tip' : getString('ZHONG_XUE')},
            '中到大雪':{'styleName' : 'weather-icon-zhongxue-daxue', 'tip' : getString('ZHONG_XUE_ZHUAN_DA_XUE')},
            '中到大雨':{'styleName' : 'weather-icon-zhongyu-dayu', 'tip' : getString('ZHONG_YU_ZHUAN_DA_YU')},
            '霾':{'styleName' : 'weather-icon-mai', 'tip' : getString('MAI')}
        };

        return _weatherMap[key] || '--';
}

function getString(key){
	return {
		zh: zh[key],
		en:en[key],
	}
}

